services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
    volumes:
      - .:/postgres

  pgadmin:
    container_name: gestao_vagas_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5432:5433"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres